#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2.

for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
done
